cabinet_app/urls.py
from django.urls import path
from cabinet_app import views as cab_app

app_name = 'cabinet_app'

urlpatterns = [
    path('', cab_app.CabinetIndexView.as_view(), name='profile'),
    path('update/<int:pk>/', cab_app.ProfileUpdateView.as_view(),
         name='profile_update'),
    path('profile_update/<int:pk>/', cab_app.ProfileUpdateView.as_view(),
         name='profile_update_data'),
    path('my_products', cab_app.MyProductListView.as_view(),
         name='my_products'),
    path('product_update/<int:pk>/', cab_app.MyProductUpdateView.as_view(),
         name='product_update'),
    path('product_update_title/<int:pk>/',
         cab_app.MyProductUpdateView.as_view(), name='product_update_title'),
    path('product_option_delete/<int:pk>/',
         cab_app.MyProductDeleteView.as_view(), name='product_option_delete'),
    path('product_delete/<int:pk>/', cab_app.MyProductDeleteView.as_view(),
         name='product_delete'),
    path('product_create/', cab_app.ProductCreateView.as_view(),
         name='product_create'),
    path('response/', cab_app.ProductResponseView.as_view(), name='response'),
    path('response_read/<int:pk>/', cab_app.ProductResponseRead.as_view(),
         name='response_read'),
]

insure/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('cabinet/', include('cabinet_app.urls', namespace='cab_app')),
    path('search/', include('search_app.urls', namespace='search_app')),
    path('about/', include('about_app.urls', namespace='about_app')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

main_app/urls.py
from django.urls import path
from main_app import views as main_app

app_name = 'main_app'

urlpatterns = [
    path('', main_app.IndexView.as_view(), name='index'),
    path('company/<int:pk>/', main_app.CompanyDetailView.as_view(),
         name='company'),
    path('category/<int:pk>/', main_app.ProductForCategoryDetailView.as_view(),
         name='category'),
    path('product/', main_app.ProductListView.as_view(), name='products'),
    path('product/<int:pk>/', main_app.ProductDetailView.as_view(),
         name='product'),
    path('response-valid/<int:pk>/', main_app.ResponseValidView.as_view(),
         name='valid'),
]

cabinet_app/models.py
from django.db import models

# Create your models here.

cabinet_app/forms.py
from django import forms

from auth_app.models import CompanyUserProfile, CompanyUser
from main_app.models import Product, ProductOption, ProductCategory


class ProfileCreateForm(forms.ModelForm):
    """Форма создания профиля компании"""

    class Meta:
        model = CompanyUserProfile
        fields = ('name', 'tax_id', 'about_company', 'label')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProfileUpdateForm(forms.ModelForm):
    """Форма изменения о компании"""

    class Meta:
        model = CompanyUserProfile
        fields = ('about_company', 'label')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProfileUpdateDataForm(forms.ModelForm):
    """Форма изменения профиля компании"""

    class Meta:
        model = CompanyUser
        fields = ('last_name', 'first_name', 'patronymic', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductOptionUpdateForm(forms.ModelForm):
    """Форма редактирования опций продукта"""

    class Meta:
        model = ProductOption
        fields = ('price', 'term', 'rate')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_price(self):
        data = self.cleaned_data['price']
        if data < 0:
            raise forms.ValidationError('Цена не может быть отрицательной')
        return data

    def clean_rate(self):
        data = self.cleaned_data['rate']
        if data < 0:
            raise forms.ValidationError(
                'Процентная ставка не может быть отрицательной')
        return data


class ProductUpdateForm(forms.ModelForm):
    """Форма редактирования продукта"""

    class Meta:
        model = Product
        fields = ('category', 'name', 'short_desc', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = ProductCategory.objects.filter(
            is_active=True)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductOptionCreateForm(forms.ModelForm):
    """Форма создания опции продукта"""
    price = forms.DecimalField(label='Цена', min_value=0)
    rate = forms.DecimalField(label='Процентная ставка', min_value=0)

    class Meta:
        model = ProductOption
        fields = ('price', 'rate', 'term',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
        self.fields['price'].widget.labels = 'цена'


class ProductCreateForm(forms.ModelForm):
    """Форма создания продукта"""

    class Meta:
        model = Product
        fields = ('category', 'name', 'short_desc', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = ProductCategory.objects.filter(
            is_active=True)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

cabinet_app/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from auth_app.models import CompanyUserProfile, CompanyUser
from cabinet_app.forms import ProfileCreateForm, ProfileUpdateForm, \
    ProfileUpdateDataForm, ProductOptionUpdateForm, ProductUpdateForm, \
    ProductCreateForm, ProductOptionCreateForm
from cabinet_app.tasks import send_email_confirm
from main_app.models import ProductCategory, ProductOption, PageHit, Product, \
    ProductResponse


class CabinetIndexView(CreateView):
    """Контроллер главной страница личного кабинета"""
    template_name = 'cabinet_app/profile.html'
    form_class = ProfileCreateForm

    def get_context_data(self, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        company_id = self.request.user.id
        company = CompanyUserProfile.objects.filter(
            company__id=company_id, company__is_active=True)
        context['title'] = 'личный кабинет'
        context['categories'] = ProductCategory.get_categories()
        context['company'] = company.filter(is_active=True).select_related()
        context['company_not_active'] = company.filter(
            is_active=False).select_related()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(self.request.POST, self.request.FILES)
        if form.is_valid():
            user = self.request.user
            profile = form.save(commit=False)
            profile.company = user
            form.save()
            send_email_confirm.delay(user.id, user.username)
        return HttpResponseRedirect(reverse('cab_app:profile'))

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProfileUpdateView(UpdateView):
    """Контроллер редактирования профиля компании"""
    success_url = reverse_lazy('cab_app:profile')

    def get_context_data(self, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = 'редактирование профиля'
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_template_names(self):
        if self.request.resolver_match.url_name == 'profile_update':
            template_name = 'cabinet_app/profile_update.html'
        else:
            template_name = 'cabinet_app/profile_update_data.html'
        return template_name

    def get_form_class(self):
        if self.request.resolver_match.url_name == 'profile_update':
            form_class = ProfileUpdateForm
        else:
            form_class = ProfileUpdateDataForm
        return form_class

    def get_queryset(self):
        if self.request.resolver_match.url_name == 'profile_update':
            queryset = CompanyUserProfile.objects.filter(
                is_active=True, company__is_active=True,
                company_id=self.request.user.id)
        else:
            queryset = CompanyUser.objects.filter(
                is_active=True, id=self.request.user.id)
        return queryset

    def form_valid(self, form):
        if self.request.resolver_match.url_name == 'profile_update_data' \
                and not self.request.user.is_staff:
            user = self.request.user
            CompanyUserProfile.objects.filter(
                company_id=user.id).update(is_active=False)
            send_email_confirm.delay(user.id, user.username)
            form.save()
            return HttpResponseRedirect(reverse('cab_app:profile'))
        return super().form_valid(form)

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class MyProductListView(ListView):
    """Контроллер списка продуктов компании"""
    model = ProductOption
    template_name = 'cabinet_app/my_products.html'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = 'мои продукты'
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_queryset(self):
        return ProductOption.objects.filter(
            is_active=True, product__is_active=True,
            product__category__is_active=True,
            product__company__is_active=True,
            product__company__company__is_active=True,
            product__company__company_id=self.request.user.id
        ).select_related()

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class MyProductUpdateView(UpdateView):
    """Контроллер редактирования продукта"""
    success_url = reverse_lazy('cab_app:my_products')

    def get_context_data(self, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = 'редактирование продукта'
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        try:
            context['page_hit'] = PageHit.objects.filter(
                url=f'/product/{self.object.id}/').first().count
        except AttributeError:
            context['page_hit'] = 0
        return context

    def get_template_names(self):
        if self.request.resolver_match.url_name == 'product_update':
            template_name = 'cabinet_app/product_update.html'
        else:
            template_name = 'cabinet_app/product_update_title.html'
        return template_name

    def get_form_class(self):
        if self.request.resolver_match.url_name == 'product_update':
            form_class = ProductOptionUpdateForm
        else:
            form_class = ProductUpdateForm
        return form_class

    def form_valid(self, form):
        if self.request.resolver_match.url_name == 'product_update':
            if not form.instance.rate:
                form.instance.rate = 0
            form.save()
            return HttpResponseRedirect(self.get_success_url())
        return super().form_valid(form)

    def get_queryset(self):
        if self.request.resolver_match.url_name == 'product_update':
            queryset = ProductOption.objects.filter(
                is_active=True, product__is_active=True,
                product__category__is_active=True,
                product__company__is_active=True,
                product__company__company__is_active=True,
                product__company__company_id=self.request.user.id
            )
        else:
            queryset = Product.objects.filter(
                is_active=True, category__is_active=True,
                company__is_active=True, company__company__is_active=True,
                company__company_id=self.request.user.id)
        return queryset

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class MyProductDeleteView(DeleteView):
    """Контроллер удаления продукта"""
    success_url = reverse_lazy('cab_app:my_products')

    def get_context_data(self, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = 'удаление продукта'
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_template_names(self):
        if self.request.resolver_match.url_name == 'product_option_delete':
            template_name = 'cabinet_app/product_option_delete.html'
        else:
            template_name = 'cabinet_app/product_delete.html'
        return template_name

    def get_queryset(self):
        if self.request.resolver_match.url_name == 'product_option_delete':
            queryset = ProductOption.objects.filter(
                is_active=True, product__is_active=True,
                product__category__is_active=True,
                product__company__is_active=True,
                product__company__company__is_active=True,
                product__company__company_id=self.request.user.id
            )
        else:
            queryset = Product.objects.filter(
                is_active=True, category__is_active=True,
                company__is_active=True, company__company__is_active=True,
                company__company_id=self.request.user.id)
        return queryset

    def form_valid(self, form):
        product = self.get_object()
        product.is_active = False
        product.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCreateView(CreateView):
    """Контроллер создания продукта"""
    template_name = 'cabinet_app/product_create.html'
    form_class = ProductCreateForm
    success_url = reverse_lazy('cab_app:my_products')
    model = Product

cabinet_app/templates/cabinet_app/my_products.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}, {{ user }}</h1>
    <div class="cabinet">
        {% include 'cabinet_app/includes/inc_menu.html' %}
        <div class="cabinet__my_products">
            {% include 'main_app/includes/inc_products.html' %}
            <div class="product_add_new">
                <a href="{% url 'cab_app:product_create' %}">Добавить новый продукт</a>
            </div>
        </div>
    </div>
{% endblock %}

cabinet_app/templates/cabinet_app/product_create.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}</h1>
    <div class="cabinet">
        {% include 'cabinet_app/includes/inc_menu.html' %}
        <div class="cabinet_content">
            <form action="{% url 'cab_app:product_create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {{ form_product.as_p }}
                <div class="profile_send">
                    <button type="submit">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

cabinet_app/templates/cabinet_app/product_delete.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}</h1>
    <br>
    <div class="cabinet_delete">
        <div class="cabinet_delete">
            <div class="a_product__content">
                <h3>Вы уверены, что хотите
                    удалить {{ object.product.name }}?</h3>
                <br>
                <hr>
                <div>
                    <h3 class="a_product__title">{{ object.name }}</h3>
                </div>
                <div class="a_product__options">
                    <div class="a_product__option"></div>
                    <div class="a_product__option">
                        <p>Компания: <a
                                href="#">{{ object.company }}</a></p>
                        <p>Категория: <a
                                href="{% url 'main_app:category' pk=object.category.id %}">{{ object.category }}</a>
                        </p>
                    </div>
                    <div class="a_product__option"></div>
                </div>
                <br>
                <form action="{% url 'cab_app:product_delete' pk=object.id %}"
                      method="post">
                    {% csrf_token %}
                    <div class="button_delete">
                        <div class="a_product_button_form">
                            <button type="button"><a href="{% url 'cab_app:product_update_title' object.id %}">Отмена</a>
                            </button>
                        </div>
                        <div class="a_product_button_form">
                            <button type="submit">Удалить</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

cabinet_app/templates/cabinet_app/product_option_delete.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}</h1>
    <br>
    <div class="cabinet_delete">
        <div class="cabinet_delete">
            <div class="a_product__content">
                <h3>Вы уверены, что хотите
                    удалить {{ object.product.name }}?</h3>
                <br>
                <hr>
                <div>
                    <h3 class="a_product__title">Характеристики:</h3>
                </div>
                <div class="a_product__options">
                    <div class="a_product__option"></div>
                    <div class="a_product__option">
                        <p>Компания: <a
                                href="#">{{ object.product.company }}</a></p>
                        <p>Категория: <a
                                href="{% url 'main_app:category' pk=object.product.category.id %}">{{ object.product.category }}</a>
                        </p>
                        <p>Срок: на {{ object.term }} мес.</p>
                        {% if object.rate != 0 %}
                            <p>Ставка: {{ object.rate }} %</p>
                        {% endif %}
                        <p>Цена: {{ object.price }} &#8381;</p>
                    </div>
                    <div class="a_product__option"></div>
                </div>
                <br>
                <form action="{% url 'cab_app:product_option_delete' pk=object.id %}"
                      method="post">
                    {% csrf_token %}
                    <div class="button_delete">
                        <div class="a_product_button_form">
                            <button type="button"><a href="{% url 'cab_app:product_update' object.id %}">Отмена</a>
                            </button>
                        </div>
                        <div class="a_product_button_form">
                            <button type="submit">Удалить</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

cabinet_app/templates/cabinet_app/product_update.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}</h1>
    <div class="cabinet">
        {% include 'cabinet_app/includes/inc_menu.html' %}
        <div class="cabinet_content">
            <form action="{% url 'cab_app:product_update' object.id %}"
                  method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <p>Просмотров: {{ page_hit }}</p>
                <div class="profile_send">
                    <button type="submit">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
    <div class="update_delete_product">
        <div class="profile_edit_link_">
            <a href="{% url 'cab_app:product_option_delete' object.id%}">Удалить этот продукт</a>
        </div>
        <div class="profile_edit_link_">
            <a href="{% url 'cab_app:product_update_title' object.product.id %}">Изменить
                описание продукта</a>
        </div>
    </div>
{% endblock %}

cabinet_app/templates/cabinet_app/product_update_title.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }} {{ object.name }}</h1>
    <div class="cabinet">
        {% include 'cabinet_app/includes/inc_menu.html' %}
        <div class="cabinet_content">
            <form class="profile_form"
                  action="{% url 'cab_app:product_update_title' object.id %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="profile_send">
                    <button type="submit">Сохранить</button>
                </div>
            </form>
        </div>
    </div>

    <div class="update_delete_product">
        <div class="profile_edit_link_">
            <a href="{% url 'cab_app:product_delete' object.id %}">Удалить {{ object.name }}</a>
        </div>
        <div class="profile_edit_link_">
            <a href="{% url 'cab_app:my_products' %}">Отмена</a>
        </div>
    </div>

{% endblock %}

cabinet_app/templates/cabinet_app/profile.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}, {{ user }}</h1>
    <div class="cabinet">
        {% include 'cabinet_app/includes/inc_menu.html' %}
        <div class="cabinet_content">
            {% if company %}
                <div class="product__label">
                    <img class="product__img" src="/media/{{ company.0.label }}"
                         alt="{{ company.0.name }}">
                </div>
                <div class="profile_company">
                    <p>Компания: <span>{{ company.0.name }}</span></p>
                    <p>Директор:
                        <span>
                                {{ company.0.company.last_name|title }}
                                {{ company.0.company.first_name|title }}
                                {{ company.0.company.patronymic|title }}
                            </span>
                    </p>
                    <p>ИНН: <span>{{ company.0.tax_id }}</span></p>
                    <p>E-mail: <span>{{ company.0.company.email }}</span></p>
                    <p>Описание: <span>{{ company.0.about_company }}</span></p>
                </div>
                <div class="profile_edit_link">
                    <a href="{% url 'cab_app:profile_update' company.0.id %}">Изменить</a>
                </div>
            {% elif company_not_active %}
                <div>
                    <div>
                        <h4>Данные вашей компании проходят проверку...</h4>
                    </div>
                    <div class="profile_company">
                        <p>Компания: <span>{{ company_not_active.0.name }}</span>
                        </p>
                        <p>Директор:
                            <span>
                                {{ company_not_active.0.company.last_name|title }}
                                {{ company_not_active.0.company.first_name|title }}
                                {{ company_not_active.0.company.patronymic|title }}
                            </span>
                        </p>
                        <p>ИНН: <span>{{ company_not_active.0.tax_id }}</span>
                        </p>
                    </div>
                </div>
            {% else %}
                <form class="profile_form" action="{% url 'cab_app:profile' %}"
                      method="post" enctype="multipart/form-data">
                    <h3>Заполните данные компании и отправьте на
                        подтверждение</h3>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="profile_send">
                        <button type="submit">Отправить</button>
                    </div>
                </form>
            {% endif %}

        </div>
    </div>
{% endblock %}

cabinet_app/templates/cabinet_app/profile_update.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}, {{ user }}</h1>
    <div class="cabinet">
        {% include 'cabinet_app/includes/inc_menu.html' %}
        <div class="cabinet_content">
            <form class="profile_form"
                  action="{% url 'cab_app:profile_update' object.id %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="profile_send">
                    <button type="submit">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
    {% if object.company.id %}
        <div class="profile_edit_link_">
            <a href="{% url 'cab_app:profile_update_data' object.company.id %}">Изменить
                профиль</a>
        </div>
    {% endif %}

{% endblock %}

cabinet_app/templates/cabinet_app/profile_update_data.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}, {{ user }}</h1>
    <div class="cabinet">
        {% include 'cabinet_app/includes/inc_menu.html' %}
        <div class="cabinet_content">
            <form class="profile_form"
                  action="{% url 'cab_app:profile_update_data' object.id %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="profile_send">
                    <button type="submit">Сохранить</button>
                </div>
            </form>
        </div>
    </div>

    {% if request.resolver_match.url_name.split.0 == 'profile_update_data' %}
        <div>
            <h3 class="update_attention">
                {% if not user.is_staff %}

                Внимание! После изменения, данные
                отправятся на
                рассмотрение... {% endif %}<a
                        href="{% url 'cab_app:profile' %}">Отмена</a></h3>
        </div>
    {% endif %}

{% endblock %}

cabinet_app/templates/cabinet_app/response.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/read_response.js' %}"></script>
{% endblock %}

{% block content %}
    <h1 class="a_product__title">{{ title|capfirst }}, {{ user }}</h1>
    <div class="cabinet">
        {% include 'cabinet_app/includes/inc_menu.html' %}
        <div class="cabinet__my_products">
            {% include 'cabinet_app/includes/inc_response.html' %}
        </div>
    </div>
{% endblock %}