insure/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('cabinet/', include('cabinet_app.urls', namespace='cab_app')),
    path('search/', include('search_app.urls', namespace='search_app')),
    path('about/', include('about_app.urls', namespace='about_app')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

main_app/urls.py
from django.urls import path
from main_app import views as main_app

app_name = 'main_app'

urlpatterns = [
    path('', main_app.IndexView.as_view(), name='index'),
    path('company/<int:pk>/', main_app.CompanyDetailView.as_view(),
         name='company'),
    path('category/<int:pk>/', main_app.ProductForCategoryDetailView.as_view(),
         name='category'),
    path('product/', main_app.ProductListView.as_view(), name='products'),
    path('product/<int:pk>/', main_app.ProductDetailView.as_view(),
         name='product'),
    path('response-valid/<int:pk>/', main_app.ResponseValidView.as_view(),
         name='valid'),
]

search_app/urls.py
from django.urls import path
from search_app import views as search_app

app_name = 'search_app'

urlpatterns = [
    path('', search_app.SearchView.as_view(), name='search'),
    path('filter/', search_app.FilterView.as_view(), name='filter'),
]

search_app/models.py
from django.db import models

# Create your models here.

search_app/views.py
from django.core.paginator import Paginator, Page
from django.views.generic import ListView
from elasticsearch import RequestError
from elasticsearch_dsl import Q

from main_app.models import ProductCategory, ProductResponse
from search_app.documents import ProductOptionDocument
from search_app.search import search_obj, elastic_filter


class DSEPaginator(Paginator):

    def __init__(self, *args, **kwargs):
        super(DSEPaginator, self).__init__(*args, **kwargs)
        self._count = self.object_list.hits.total

    def page(self, number):
        number = self.validate_number(number)
        return Page(self.object_list, number, self)


class SearchView(ListView):
    """Elastic поиск"""
    template_name = 'search_app/search.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = 'Поиск по запросу:'
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_queryset(self):
        query = self.request.GET.get('search')
        try:
            q = Q(
                'multi_match',
                query=query,
                fields=[
                    'product.name', 'product.category.name',
                    'product.company.name', 'product.short_desc',
                    'product.description',
                ],
                fuzziness='auto',
            )
            object_list = search_obj(q)

            if object_list.count() == 0:
                try:
                    query = int(query)
                    q = Q(
                        'multi_match',
                        query=query,
                        fields=[
                            'price', 'rate', 'term'
                        ]
                    )
                    object_list = search_obj(q)
                except ValueError:
                    pass
        except RequestError:
            object_list = []
        object_list = elastic_filter(object_list)
        return object_list


class FilterView(ListView):
    """Elastic filter"""
    template_name = 'search_app/search.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = ProductCategory.get_categories()
        context['title'] = 'Фильтр'
        context['categories'] = categories
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_queryset(self):
        categories = ProductCategory.get_categories()
        request_get = self.request.GET

        category_filter = []
        for category in categories:
            if request_get.get(category.name):
                category_filter.append(category.name)

        min_price = request_get.get('min_price')
        max_price = request_get.get('max_price')
        min_term = request_get.get('min_term')
        max_term = request_get.get('max_term')
        min_rate = request_get.get('min_rate')
        max_rate = request_get.get('max_rate')

        object_list = ProductOptionDocument.search()

        if category_filter:
            i = 0
            q = Q(
                'multi_match',
                query=category_filter[i],
                fields=[
                    'product.category.name'
                ]
            )
            while i < len(category_filter):
                q |= Q(
                    'multi_match',
                    query=category_filter[i],
                    fields=[
                        'product.category.name'
                    ]
                )
                i += 1
            object_list = object_list.query(q)
        if min_price:
            object_list = object_list.filter('range', price={'gte': min_price})
        if max_price:
            object_list = object_list.filter('range', price={'lte': max_price})
        if min_term:
            object_list = object_list.filter('range', term={'gte': min_term})
        if max_term:
            object_list = object_list.filter('range', term={'lte': max_term})
        if min_rate:
            object_list = object_list.filter('range', rate={'gte': min_rate})
        if max_rate:
            object_list = object_list.filter('range', rate={'lte': max_rate})

        object_list = elastic_filter(object_list)
        return object_list

search_app/templates/search_app/search.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    {% include 'main_app/includes/inc_sort.html' %}
    
    <h1 class="all_products">{{ title }} {{ request.GET.search }}</h1>
    {% if search.count != 0 %}
        {% for product in object_list %}
            <div class="product">
                <div class="product__label">
                    <img class="product__img"
                         src="{{ product.product.company.label }}"
                         alt="{{ product.product.company.name }}">
                    <a class="product__company" href="#">
                        <p>{{ product.product.company.name }}</p></a>
                </div>
                <div class="product__info">
                    <p class="product__category">Категория:
                        <span>{{ product.product.category.name }}</span></p>
                    <a class="product__name"
                       href="{% url 'main_app:product' pk=product.id %}">
                        <p>{{ product.product.name }}</p></a>
                    <p class="product__description">{{ product.product.short_desc }}</p>
                </div>
                <div class="product__info_2">
                    <p class="product__term">На <span>{{ product.term }}</span>
                        мес.
                    </p>
                    <p class="product__price"><span>{{ product.price }}</span>
                        &#8381;
                    </p>
                    {% if product.rate != 0 %}
                        <p class="product__rate">Ставка:
                            <span>{{ product.rate }} %</span></p>
                    {% endif %}
                </div>
                <div class="product__button">
                    <a href="{% url 'main_app:product' pk=product.id %}">
                        Посмотреть
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>Ничего не найдено...</h3>
    {% endif %}

{% endblock %}