about_app/urls.py
from django.urls import path
from about_app import views as about_app

app_name = 'about_app'

urlpatterns = [
    path('contacts/', about_app.ContactView.as_view(), name='contacts'),
    path('feedback/', about_app.FeedbackView.as_view(), name='feedback'),
    path('information/', about_app.InformationView.as_view(),
         name='information'),
    path('politics/', about_app.PoliticsView.as_view(), name='politics'),
    path('cookies/', about_app.CookieView.as_view(), name='cookie'),
]

auth_app/urls.py
from django.urls import path
from auth_app import views as auth_app

app_name = 'auth_app'

urlpatterns = [
    path('register/', auth_app.RegisterView.as_view(), name='register'),
    path('register-valid/', auth_app.RegisterValidView.as_view(),
         name='register_valid'),
    path('verify/<email>/<activation_key>/', auth_app.VerifyView.as_view(),
         name='verify'),
    path('login/', auth_app.LoginUserView.as_view(), name='login'),
    path('logout/', auth_app.LogoutUserView.as_view(), name='logout'),
]

cabinet_app/urls.py
from django.urls import path
from cabinet_app import views as cab_app

app_name = 'cabinet_app'

urlpatterns = [
    path('', cab_app.CabinetIndexView.as_view(), name='profile'),
    path('update/<int:pk>/', cab_app.ProfileUpdateView.as_view(),
         name='profile_update'),
    path('profile_update/<int:pk>/', cab_app.ProfileUpdateView.as_view(),
         name='profile_update_data'),
    path('my_products', cab_app.MyProductListView.as_view(),
         name='my_products'),
    path('product_update/<int:pk>/', cab_app.MyProductUpdateView.as_view(),
         name='product_update'),
    path('product_update_title/<int:pk>/',
         cab_app.MyProductUpdateView.as_view(), name='product_update_title'),
    path('product_option_delete/<int:pk>/',
         cab_app.MyProductDeleteView.as_view(), name='product_option_delete'),
    path('product_delete/<int:pk>/', cab_app.MyProductDeleteView.as_view(),
         name='product_delete'),
    path('product_create/', cab_app.ProductCreateView.as_view(),
         name='product_create'),
    path('response/', cab_app.ProductResponseView.as_view(), name='response'),
    path('response_read/<int:pk>/', cab_app.ProductResponseRead.as_view(),
         name='response_read'),
]

insure/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('cabinet/', include('cabinet_app.urls', namespace='cab_app')),
    path('search/', include('search_app.urls', namespace='search_app')),
    path('about/', include('about_app.urls', namespace='about_app')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

main_app/urls.py
from django.urls import path
from main_app import views as main_app

app_name = 'main_app'

urlpatterns = [
    path('', main_app.IndexView.as_view(), name='index'),
    path('company/<int:pk>/', main_app.CompanyDetailView.as_view(),
         name='company'),
    path('category/<int:pk>/', main_app.ProductForCategoryDetailView.as_view(),
         name='category'),
    path('product/', main_app.ProductListView.as_view(), name='products'),
    path('product/<int:pk>/', main_app.ProductDetailView.as_view(),
         name='product'),
    path('response-valid/<int:pk>/', main_app.ResponseValidView.as_view(),
         name='valid'),
]

search_app/urls.py
from django.urls import path
from search_app import views as search_app

app_name = 'search_app'

urlpatterns = [
    path('', search_app.SearchView.as_view(), name='search'),
    path('filter/', search_app.FilterView.as_view(), name='filter'),
]

main_app/forms.py
from django import forms
from main_app.models import ProductResponse


class ProductResponseCreateForm(forms.ModelForm):
    """Форма отклика на продукт"""

    class Meta:
        model = ProductResponse
        fields = (
            'first_name', 'last_name', 'patronymic', 'email', 'phone_number')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.help_text = ''
        self.fields['patronymic'].required = False
        self.fields['first_name'].widget.attrs['placeholder'] = 'Иван'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Иванов'
        self.fields['patronymic'].widget.attrs['placeholder'] = 'Иванович'
        self.fields['email'].widget.attrs['placeholder'] = 'email@email.ru'
        self.fields['phone_number'].widget.attrs[
            'placeholder'] = '+79999999999'
        self.fields['phone_number'].widget.attrs[
            'pattern'] = r'^\+7\d{10,10}$'
        self.fields['phone_number'].widget.attrs[
            'oninvalid'] = "this.setCustomValidity('Неверный номер " \
                           "телефона...')"
        self.fields['phone_number'].widget.attrs[
            'oninput'] = "setCustomValidity('')"

main_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView

from main_app.decorators import counted
from main_app.forms import ProductResponseCreateForm
from main_app.models import ProductCategory, ProductOption, ProductResponse, \
    PageHit
from main_app.tasks import send_email_company
from auth_app.models import CompanyUserProfile


class IndexView(ListView):
    """Контроллер главной страницы"""
    template_name = 'main_app/index.html'
    model = ProductOption

    def get_context_data(self, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = 'главная'
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_queryset(self):
        populate_objects = PageHit.objects.all().order_by(
            '-updated').order_by('-count')[:3]
        populate_products = [i.url.split('/')[-2] for i in populate_objects]
        queryset = self.model.objects.filter(
            id__in=populate_products, is_active=True,
            product__is_active=True, product__category__is_active=True,
            product__company__is_active=True,
            product__company__company__is_active=True).select_related()
        return queryset


class ProductForCategoryDetailView(ListView):
    """Контроллер списка продуктов для категории"""
    model = ProductCategory
    template_name = 'main_app/category.html'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        """Возвращает контекст для этого представления"""
        queryset = ProductOption.get_product_for_category(
            category=self.kwargs['pk']).select_related()
        context = super().get_context_data(**kwargs, object_list=queryset)
        categories = ProductCategory.get_categories()
        context['title'] = categories.filter(id=self.kwargs['pk']).first()
        context['categories'] = categories
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_queryset(self):
        """Возвращает список элементов для этого представления"""
        return get_object_or_404(self.model, pk=self.kwargs['pk'])


class ProductListView(ListView):
    """Контроллер списка продуктов"""
    template_name = 'main_app/products.html'
    model = ProductOption
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = 'продукты'
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_queryset(self):
        """Возвращает список элементов для этого представления"""
        object_list = ProductOption.objects.filter(
            is_active=True,
            product__is_active=True,
            product__category__is_active=True,
            product__company__is_active=True,
            product__company__company__is_active=True).select_related()

        # category_filter = []
        # request_get = self.request.GET
        #
        # categories = ProductCategory.get_categories()
        # for category in categories:
        #     if request_get.get(category.name) is not None:
        #         category_filter.append(category)
        #
        # min_price = request_get.get('min_price')
        # max_price = request_get.get('max_price')
        # min_term = request_get.get('min_term')
        # max_term = request_get.get('max_term')
        # min_rate = request_get.get('min_rate')
        # max_rate = request_get.get('max_rate')
        # # search = request_get.get('search')
        #
        # if category_filter:
        #     object_list = object_list.filter(
        #         product__category__in=category_filter)
        # if min_price:
        #     object_list = object_list.filter(price__gte=min_price)
        # if max_price:
        #     object_list = object_list.filter(price__lte=max_price)
        # if min_term:
        #     object_list = object_list.filter(term__gte=min_term)
        # if max_term:
        #     object_list = object_list.filter(term__lte=max_term)
        # if min_rate:
        #     object_list = object_list.filter(rate__gte=min_rate)
        # if max_rate:
        #     object_list = object_list.filter(rate__lte=max_rate)
        # # if search:
        # #     if DATABASES['default']['NAME'] == 'insure':
        # #         vector = SearchVector('product__name',
        # #                               'product__category__name',
        # #                               'product__company__name')
        # #         query = SearchQuery(search)
        # #         object_list = object_list.annotate(
        # #             rank=SearchRank(vector, query)).order_by('-rank')
        # #     else:
        # #         query_string = self.request.GET['search']
        # #         entry_query = get_query(query_string,
        # #                                 ['product__name'])
        # #         object_list = object_list.filter(entry_query)

        return object_list


class ProductDetailView(DetailView):
    """Контроллер продукта"""
    template_name = 'main_app/product.html'
    model = ProductOption

    @counted
    def get_context_data(self, *, object_list=None, **kwargs):
        """Возвращает контекст для этого представления"""
        form = ProductResponseCreateForm()
        context = super().get_context_data(**kwargs)
        context['form'] = form
        context['title'] = self.object.product.name
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def post(self, request, *args, **kwargs):
        """Добавление заявки в базу"""
        form = ProductResponseCreateForm(data=self.request.POST)
        if form.is_valid():
            create_response = form.save(commit=False)
            create_response.product = self.model.objects.get(
                id=self.kwargs['pk'])
            form.save(commit=True)
            instance = form.instance
            send_email_company.delay(
                phone=instance.phone_number, email=instance.email,
                first_name=instance.first_name, last_name=instance.last_name,
                product_name=instance.product.product.name,
                company_email=instance.product.product.company.company.email
            )
            return HttpResponseRedirect(
                reverse('main_app:valid', args=[kwargs['pk']]))
        return HttpResponseRedirect(
            reverse('main_app:product', args=[kwargs['pk']]))

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_active=True, product__is_active=True,
                               product__category__is_active=True,
                               product__company__is_active=True,
                               product__company__company__is_active=True)


class ResponseValidView(DetailView):
    """Контроллер удачной заявки"""
    template_name = 'main_app/response_valid.html'
    model = ProductOption

    def get_context_data(self, *, object_list=None, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.product.name
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_active=True, product__is_active=True,
                               product__category__is_active=True,
                               product__company__is_active=True,
                               product__company__company__is_active=True)


class CompanyDetailView(DetailView):
    """Контроллер компании"""
    template_name = 'main_app/company.html'
    model = CompanyUserProfile

    def get_context_data(self, *, object_list=None, **kwargs):
        """Возвращает контекст для этого представления"""
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        context['categories'] = ProductCategory.get_categories()
        context['response_length'] = ProductResponse.get_response_length(
            self.request.user.id)
        return context

main_app/templates/main_app/includes/inc_header.html
{% load static %}
<a class="header__icon" href="{% url 'main_app:index' %}">
    <img class="header__img" src="{% static 'img/icon.svg' %}"
         alt="icon">
</a>

<a {% if request.resolver_match.url_name.split.0 == 'index' %}class="header__menu active"
   {% else %}class="header__menu"{% endif %}
   href="{% url 'main_app:index' %}">
    <h3>Главная</h3>
</a>

<a {% if request.resolver_match.url_name.split.0 == 'product' or request.resolver_match.url_name.split.0 == 'products' %}class="header__menu active"
   {% else %}class="header__menu"{% endif %}
   href="{% url 'main_app:products' %}">
    <h3>Продукты</h3>
</a>

<div class="dropdown header__menu">
    <button
            {% if request.resolver_match.url_name.split.0 == 'category' %}class="drop__btn active"
            {% else %}class="drop__btn"{% endif %}>
        <h3>Категории</h3>
    </button>
    <div class="dropdown-content">
        {% for category in categories %}
            <a href="{% url 'main_app:category' pk=category.id %}">{{ category }}</a>
        {% endfor %}
    </div>
</div>

<div class="dropdown header__menu">
    <button {% if request.resolver_match.url_name.split.0 == 'contacts' or request.resolver_match.url_name.split.0 == 'feedback' or request.resolver_match.url_name.split.0 == 'information' or request.resolver_match.url_name.split.0 == 'cookie' or request.resolver_match.url_name.split.0 == 'politics' %}
        class="drop__btn active"
        {% else %}class="drop__btn"{% endif %}>
        <h3>О нас</h3>
    </button>
    <div class="dropdown-content">
        <a href="{% url 'about_app:contacts' %}">Контакты</a>
        <a href="{% url 'about_app:information' %}">Правовая информация</a>
        <a href="{% url 'about_app:politics' %}">Политика конфиденциальности</a>
        <a href="{% url 'about_app:cookie' %}">Cookies</a>
        <a href="{% url 'about_app:feedback' %}">Обратная связь</a>
        <a href="{% static 'documentation/_build/html/index.html' %}">Документация</a>
    </div>
</div>

{% include 'main_app/includes/inc_search.html' %}
<p id="response_length" class="response_length">{{ response_length }}</p>
<a id="header_images" class="header__login" href="{% url 'auth_app:login' %}">
    {% if response_length %}
        <img id="header_img" class="header_img"
             src="{% static 'img/bell.gif' %}" alt="icon">
    {% else %}
        <img id="header_img" class="header__img"
             src="{% static 'img/user.svg' %}"
             alt="icon">
    {% endif %}
</a>

main_app/templates/main_app/includes/inc_paginator.html
{% load url_replace %}

{% if page_obj != None %}
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?{% url_replace page=page_obj.previous_page_number %}"> ◀️ </a>
        {% endif %}

        <span class="current">
            Страница №{{ page_obj.number }}
        </span>

        {% if page_obj.has_next %}
            <a href="?{% url_replace page=page_obj.next_page_number %}"> ▶️ </a>
        {% endif %}
    </span>
    </div>
{% endif %}

main_app/templates/main_app/includes/inc_products.html
{% if object_list %}
    {% for product in object_list %}
        <div class="product">
            <div class="product__label">
                <img class="product__img"
                     src="/media/{{ product.product.company.label }}"
                     alt="{{ product.product.company }}">
                <a class="product__company" href="{% url 'main_app:company' product.product.company.id %}">
                    <p>{{ product.product.company }}</p></a>
            </div>
            <div class="product__info">
                <p class="product__category">Категория:
                    <span>{{ product.product.category }}</span></p>
                {% if request.resolver_match.url_name != 'my_products' %}
                <a class="product__name"
                   href="{% url 'main_app:product' pk=product.id %}">
                    <p>{{ product.product.name }}</p></a>
                {% else %}
                    <a class="product__name"
                   href="{% url 'cab_app:product_update' pk=product.id %}">
                    <p>{{ product.product.name }}</p></a>
                {% endif %}
                <p class="product__description">{{ product.product.short_desc }}</p>
            </div>
            <div class="product__info_2">
                <p class="product__term">На <span>{{ product.term }}</span>
                    мес.
                </p>
                <p class="product__price"><span>{{ product.price }}</span>
                    &#8381;
                </p>
                {% if product.rate != 0 %}
                    <p class="product__rate">Ставка:
                        <span>{{ product.rate }} %</span></p>
                {% endif %}
            </div>
            <div class="product__button">
                {% if request.resolver_match.url_name != 'my_products' %}
                    <a href="{% url 'main_app:product' pk=product.id %}">
                        Посмотреть
                    </a>
                {% else %}
                    <a href="{% url 'cab_app:product_update' pk=product.id %}">
                        Редактировать
                    </a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% else %}
    <h3>Ничего не найдено...</h3>
{% endif %}

main_app/templates/main_app/includes/inc_search.html
<form action="{% url 'search_app:search' %}">
    <div class="form__search">
        <label>
            <input class="header__input" type="text"
{#                   oninvalid="this.setCustomValidity('Введите то, что хотите найти...')"#}
{#                   oninput="setCustomValidity('')"#}
                   placeholder="поиск..."
                   name="search" value="{{ request.GET.search }}">
        </label>
        <button class="header__button" type="submit">🔎</button>
    </div>
</form>

main_app/templates/main_app/includes/inc_sort.html
<div class="sort">
    <div class="dropdown">
        <button class="drop__btn">
            <p class="sort__text">Фильтровать по:</p>
        </button>
        <form action="{% url 'search_app:filter' %}">
            <div class="dropdown-content-filter">
                <p>Категории</p>
                {% for category in categories %}
                    <span><label>
                    <input type="checkbox" name="{{ category }}" value="true"
                           {% if category.name in request.GET %}
                           checked="checked"
                           {% elif category.id == request.resolver_match.kwargs.pk %}
                           checked="checked"
                           {% endif %}>
                </label> {{ category }}</span>
                {% endfor %}
                <p>Цене</p>
                <div class="filter-controls">
                    <label class="min">от <input type="number"
                                                 name="min_price"
                                                 placeholder="..."
                                                 value="{{ request.GET.min_price }}"
                    >-</label>
                    <label class="max">до <input type="number"
                                                 name="max_price"
                                                 placeholder="..."
                                                 value="{{ request.GET.max_price }}"
                    ></label>
                </div>
                <p>Сроку</p>
                <div class="filter-controls">
                    <label class="min">от <input type="number"
                                                 name="min_term"
                                                 placeholder="..."
                                                 value="{{ request.GET.min_term }}"
                    >-</label>
                    <label class="max">до <input type="number"
                                                 name="max_term"
                                                 placeholder="..."
                                                 value="{{ request.GET.max_term }}"
                    ></label>
                </div>
                <p>Процентной ставке</p>
                <div class="filter-controls">
                    <label class="min">от <input type="number"
                                                 name="min_rate"
                                                 placeholder="..."
                                                 value="{{ request.GET.min_rate }}"
                    >-</label>
                    <label class="max">до <input type="number"
                                                 name="max_rate"
                                                 placeholder="..."
                                                 value="{{ request.GET.max_rate }}"
                    ></label>
                </div>
                <div class="filter__button">
                    <button type="submit">Применить фильтр</button>
                </div>
                <div class="filter__clear">
                    <a href="{% url 'main_app:products' %}">Отменить фильтр</a>
                </div>
            </div>
        </form>
    </div>
</div>